name: Python package

on: [push]

jobs:
  build_independencies:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.6'
          cache: 'pip'

      - name: Python Dependency Installation
        uses: py-actions/py-dependency-install@v4.0.0
        with: 
          path: "path/to/requirements.txt"
          update-pip: "false"
          update-setuptools: "false"
          update-wheel: "false"
          
      - name: Test with pytest
        run: |
          pytest
