name: Send Oil Notify

on:
  schedule:
    - cron: '45 14 * * 0'  # 每週日的中午（UTC時間）
# on:
#   push:
#     branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - id: repo
        name: Checkout code
        uses: actions/checkout@v3

      - id: package
        name: Set up Python & Independencies
        uses: actions/setup-python@v4
        with:
          python-version: "3.9.13"  # 指定所需的 Python 版本
          cache: 'pip' # caching pip dependencies
        # run: pip install -r requirements.txt
        run: pip install -r jup.txt  #jupyterbook exec file

      - id: ipynb
        name: Jupyterbook execution
        run: jupyter execute oil_notify.ipynb
        shell: bash

      # - name: Run Python Script
      #   run: python oil_notify.py  # 執行您的 Python 腳本
