name: Oil Notify

on:
  workflow_dispatch:      # 手動啟用工作流
  schedule:
    - cron: '30 12 * * 0'  # 每週日的中午（UTC時間）
# on:
#   push:
#     branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python & Independencies
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"  # 指定所需的 Python 版本
          
      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Jupyterbook execution
        run: jupyter execute oil_notify.ipynb
        shell: bash

      # - name: Run Python Script
      #   run: python oil_notify.py  # 執行您的 Python 腳本
