name: Run Python Script

# on:
#   schedule:
#     - cron: '45 2 * * 6'  # 每週日的中午（UTC時間）
on:
  push:
    branches: [ "main" ]

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: "3.9.13"  # 指定所需的 Python 版本
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f setup.txt ]; then pip install -r setup.txt; 

      - name: Run Python Script
        run: oil_notify.py  # 執行您的 Python 腳本
